apiVersion: v1
stringData:
  git_secret_token: ENC(MqCt6UKBcMTiYOEUx4MuGn0pHg6YLDX7Tmllsd4ANc3hk2lVKe7rmtH2YMFe57PMRopx3DiCJk0=)
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  git_pr_token: ''
kind: Secret
metadata:
  name: git-token
type: Opaque
