apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(8tjwBYM3bUVrdJ1Hpx2eEehmgfWbrbS3)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
